# Generated by Django 3.1.1 on 2020-10-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=220)),
                ('author', models.CharField(max_length=70)),
                ('duration', models.CharField(max_length=70)),
                ('o_price', models.CharField(max_length=70)),
                ('s_price', models.CharField(max_length=70)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
