# Generated by Django 3.1.1 on 2020-10-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_addlesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addlesson',
            options={'verbose_name': 'Addlesson', 'verbose_name_plural': 'Addlessons'},
        ),
    ]
