# Generated by Django 3.1.1 on 2020-10-11 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_auto_20201011_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addlesson',
            options={},
        ),
    ]
