# Generated by Django 3.1.1 on 2020-10-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20201011_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addlesson',
            options={'verbose_name': 'video_link', 'verbose_name_plural': 'video'},
        ),
    ]
