# Generated by Django 3.1.1 on 2020-10-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20201011_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contant', models.TextField(max_length=255)),
                ('stu_id', models.CharField(max_length=70)),
            ],
        ),
        migrations.AlterModelOptions(
            name='addlesson',
            options={},
        ),
        migrations.AlterField(
            model_name='addlesson',
            name='video_link',
            field=models.FileField(upload_to='video/'),
        ),
    ]
