# Generated by Django 3.1.1 on 2020-10-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=70)),
                ('stu_email', models.EmailField(max_length=70)),
                ('stu_pass', models.CharField(max_length=70)),
                ('con_pass', models.CharField(max_length=70)),
                ('stu_occ', models.CharField(blank=True, max_length=70)),
                ('stu_img', models.TextField(default='default.jpg', max_length=170)),
            ],
        ),
    ]
