# Generated by Django 3.1.1 on 2020-10-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='stu_img',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
    ]
