# Generated by Django 3.1.1 on 2020-10-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0003_auto_20201020_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='student_email',
            field=models.EmailField(max_length=70),
        ),
    ]
