# Generated by Django 3.1.1 on 2020-10-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0004_auto_20201020_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='student_email',
            field=models.CharField(max_length=70),
        ),
    ]
