# Generated by Django 3.1.1 on 2020-10-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpanel', '0006_auto_20201021_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
