# Generated by Django 3.1.1 on 2020-10-22 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20201014_1540'),
        ('userpanel', '0007_auto_20201021_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.addcourse'),
        ),
    ]
