# Generated by Django 3.1.1 on 2020-12-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_login_admin'),
        ('userpanel', '0009_auto_20201109_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorder',
            name='course_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.addcourse'),
        ),
    ]
